### ISSUE TITLE
DNS for home network with dnsmasq: doesn't change IPs

### ISSUE THREAD

**Issue by Drewshg312** [meastman/dnsmasq#1]
I've got a home network: three hosts on OS X and printer. All the devices are wireless and connected into a network via Actiontech T1200H router which is also provides internet. One computer(MacPro) works as a server and never switched off.

But for now DNS and DHCP services provided by router (which I've got from my ISP)...

Is it possible to use Dnsmasq to override the services provided by router?

my **dnsmasq.conf**:

    port=5353
    interface=en2
    dhcp-range=192.168.1.70,192.168.1.250,12h

    # Static IP addresses for home WLAN:
    dhcp-host=c8:bc:c8:d4:49:e8,my.macbookpro.local,192.168.1.60
    dhcp-host=80:00:6e:f1:c3:44,my.macpro.local,192.168.1.61
    dhcp-host=84:85:46:97:4C:95,my.ipad.local,192.168.1.62
    dhcp-host=00:46:ab:6c:f7:fc,my.epson.local,192.168.1.63
    
    expand-hosts
    domain=drew-sh.org

    # My router's IP:
    dhcp-option=option:router,192.168.1.254
    
    # Web dev settings:
    address=/.dev/127.0.0.1
    # to listen for DHCP and DNS requests on addresses:
    listen-address=127.0.0.1

    # Google public DNS:
    server=8.8.8.8
    server=8.8.4.4

I've restarted dnsmasq multiple times, but old IP addresses of all devices did not change... What am I doing wriong?

**Comment by meastman** [comment]
This is just a fork of the upstream repo with a few changes that were useful for me. You may want to contact the actual maintainer of dnsmasq. Documentation and contact information is here: http://www.thekelleys.org.uk/dnsmasq/doc.html

You will probably need to disable the DHCP server running on your router; otherwise, DHCP clients on your network will get offers from both DHCP servers. Also, you'll have to get your clients to renew their DHCP leases before they'll get the new addresses.

**Comment by Drewshg312** [comment]
ok thanx
